---
- name: Add couchdb stable repository from PPA.
  apt_repository:
    repo: 'ppa:couchdb/stable'

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure couchdb is installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - couchdb
